# Color constants
BACKGROUND_DARK_GRAY = "#2E2E2E"
BACKGROUND_BLACK = "#1C1C1C"
BACKGROUND_SOFT_BLACK = "#1A1A1A"
FOREGROUND_LIGHT_GRAY = "#D3D3D3"
FOREGROUND_WHITE = "#FFFFFF"
FOREGROUND_SOFT_WHITE = "#EEEEEE"
ACCENT_BLUE = "#4A90E2"
